workspace 'SimpleApp.xcworkspace'

platform :ios, '8.0'
use_frameworks!

def share_pods
	pod 'OpenShare'
	pod 'FMDB'
	pod 'YYModel'
	pod 'EGOCache'
	pod 'Masonry'
	pod 'WSProgressHUD'
	pod 'AFNetworking'
   	pod 'MJRefresh'
    pod 'SDWebImage'
	pod 'MJExtension'
    pod 'pop'
    pod 'YTKNetwork'
    pod 'WebViewJavascriptBridge'
    pod 'FBMemoryProfiler'
    pod 'Aspects'
    pod 'IQKeyboardManager'
    pod 'ReactiveObjC', '~>3.0.0'
#    pod 'MLeaksFinder'
    pod 'JDFlipNumberView'
    pod 'FLEX', :configuration => 'Debug'
    pod 'LLDebugTool' ,:configurations => ['Debug']
    pod 'AdhocSDK'
end


def swift_pods
    pod 'Then'
#    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'SnapKit'
    pod 'PromiseKit'
    pod 'Charts'
end


target 'SimpleApp' do
	project 'SimpleApp.project'
	share_pods
    swift_pods
end
