workspace 'SimpleApp.xcworkspace'

platform :ios, '8.0'

def share_pods
	pod 'OpenShare'
	pod 'FMDB'
	pod 'YYModel'
	pod 'EGOCache'
	pod 'Masonry'
	pod 'WSProgressHUD'
	pod 'AFNetworking'
   	pod 'MJRefresh'
    pod 'SDWebImage'
	pod 'MJExtension'
    pod 'pop'
    pod 'YTKNetwork'
    pod 'WebViewJavascriptBridge'
    pod 'FBMemoryProfiler'
end

target 'SimpleApp' do
	xcodeproj 'SimpleApp.xcodeproj'
	share_pods
end
